name: Search Model Check / Parity Reminder

on:
  pull_request:
    paths:
      - 'src/main/java/nucleus/model/search/**'
    branches:
      - '**'

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Find Changed Files
        id: find_changes
        run: |
          changed_files=$(git diff --name-only HEAD~1 -- 'src/main/java/nucleus/model/search/')
          
          if [ -n "$changed_files" ]; then
            echo "Found changes to files in search directory
            echo "::set-output name=directory_changed::true
          else
            echo "No changes in the search directory."
            echo "::set-output name=directory_changed::false"
          fi

      - name: Comment a reminder on the PR
        if: steps.find_changes.outputs.directory_changed == 'true'
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            🚨 Changes have been detected in the search-model directory. Please ensure to update any corresponding models in NucleusSDK to maintain parity.
